AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB table for Todo App

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Notable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  TodoTableArn:
    Description: ARN of the TodoItems DynamoDB table
    Value: !GetAtt TodoTable.Arn